# Example GitHub Actions Workflow for NixOS Configuration Testing
# This workflow can be used to automatically test NixOS configurations
# Place this in .github/workflows/ to enable it

name: Test NixOS Configuration

on:
  push:
    branches:
      - main
      - 'copilot/**'
  pull_request:
    branches:
      - main

jobs:
  validate-flake:
    name: Validate Nix Flake
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true

      - name: Setup Cachix (optional - for caching builds)
        uses: cachix/cachix-action@v12
        with:
          name: pantherOS
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        continue-on-error: true

      - name: Check flake
        run: nix flake check --all-systems

      - name: Show flake outputs
        run: nix flake show

  build-configurations:
    name: Build NixOS Configurations
    runs-on: ubuntu-latest
    needs: validate-flake
    strategy:
      matrix:
        config:
          - hetzner-vps
          - ovh-vps
          # Add other configurations as needed
      fail-fast: false
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true

      - name: Setup Cachix
        uses: cachix/cachix-action@v12
        with:
          name: pantherOS
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        continue-on-error: true

      - name: Build ${{ matrix.config }}
        run: |
          nix build .#nixosConfigurations.${{ matrix.config }}.config.system.build.toplevel \
            --show-trace \
            --print-build-logs

      - name: Check closure size
        run: |
          nix path-info -Sh .#nixosConfigurations.${{ matrix.config }}.config.system.build.toplevel

  format-check:
    name: Check Nix Formatting
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Check formatting with nixpkgs-fmt
        run: |
          nix shell nixpkgs#nixpkgs-fmt -c nixpkgs-fmt --check .

  deploy-to-vps:
    name: Deploy to VPS (if enabled)
    runs-on: ubuntu-latest
    needs: [validate-flake, build-configurations]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    # Only run on main branch pushes, and only if secrets are configured
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/vps_key
          chmod 600 ~/.ssh/vps_key
          cat >> ~/.ssh/config << EOF
          Host vps
            HostName ${{ secrets.VPS_HOST }}
            User ${{ secrets.VPS_USER }}
            Port ${{ secrets.VPS_PORT || 22 }}
            IdentityFile ~/.ssh/vps_key
            StrictHostKeyChecking accept-new
          EOF
        if: secrets.VPS_SSH_KEY != ''

      - name: Test VPS connection
        run: ssh vps 'echo "Connected to VPS"'
        if: secrets.VPS_SSH_KEY != ''

      - name: Push configuration to VPS
        run: |
          rsync -avz \
            --exclude='.git' \
            --exclude='result' \
            --exclude='.github' \
            ./ vps:~/pantherOS/
        if: secrets.VPS_SSH_KEY != ''

      - name: Build on VPS
        run: |
          ssh vps 'cd ~/pantherOS && nixos-rebuild build --flake .#hetzner-vps'
        if: secrets.VPS_SSH_KEY != ''

      - name: Dry-run on VPS
        run: |
          ssh vps 'cd ~/pantherOS && nixos-rebuild dry-build --flake .#hetzner-vps'
        if: secrets.VPS_SSH_KEY != ''

      # Note: Automatic apply is commented out for safety
      # Uncomment if you want automatic deployments
      # - name: Apply configuration on VPS
      #   run: |
      #     ssh vps 'cd ~/pantherOS && sudo nixos-rebuild switch --flake .#hetzner-vps'
      #   if: secrets.VPS_SSH_KEY != ''

  # Optional: Integration tests
  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    needs: build-configurations
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Run NixOS tests
        run: |
          # Run any integration tests defined in tests/integration/
          if [ -d tests/integration ]; then
            nix build .#checks.x86_64-linux -L
          fi
        continue-on-error: true

  # Optional: Security scanning
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run security checks
        run: |
          # Add security scanning tools here
          # For example: scan for secrets, vulnerable dependencies, etc.
          echo "Security scan placeholder"
        continue-on-error: true

# Required secrets (configure in repository settings):
# - CACHIX_AUTH_TOKEN (optional, for build caching)
# - VPS_SSH_KEY (required for VPS deployment)
# - VPS_HOST (required for VPS deployment)
# - VPS_USER (required for VPS deployment)
# - VPS_PORT (optional, defaults to 22)
