# hosts/yoga/default.nix
# Yoga host configuration using nixos-facter-modules for automatic hardware detection

{
  config,
  lib,
  pkgs,
  ...
}:

{
  imports = [
    # Core modules
    ../../modules

    # Hardware detection using nixos-facter-modules
    # This automatically configures network, graphics, USB, and other hardware
    # based on the hardware report generated by nixos-facter

    # Disk partitioning
    ./disko.nix
  ];



  # Hostname
  networking.hostName = "yoga";

  # Bootloader - GRUB with UEFI support
  boot.loader.grub = {
    enable = true;
    efiSupport = true;
    efiInstallAsRemovable = true;
    device = "nodev";
    extraConfig = ''
      serial --unit=0 --speed=115200 --word=8 --parity=no --stop=1
      terminal_input serial console
      terminal_output serial console
    '';
  };

  # SSH configuration - hardened
  services.openssh = {
    enable = true;
    settings = {
      PermitRootLogin = "prohibit-password";
      PasswordAuthentication = false;
      KbdInteractiveAuthentication = false;
    };
  };

  # User configuration
  users.users.root = {
    # OpNix writes to /root/.ssh/authorized_keys
  };

  users.users.hbohlen = {
    isNormalUser = true;
    extraGroups = [
      "wheel" # sudo access
      "podman" # container management
      "docker" # docker CLI compat
    ];
    # OpNix writes to /home/hbohlen/.ssh/authorized_keys
  };

  # Sudo configuration - passwordless for wheel group
  security.sudo.wheelNeedsPassword = false;

  # Automatic garbage collection
  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than 30d";
  };

  # Optimize nix store
  nix.settings = {
    auto-optimise-store = true;
    experimental-features = [
      "nix-command"
      "flakes"
    ];
  };

  # File systems configured by disko.nix

    # DankMaterialShell - Material design shell environment
    # TODO: Fix network/build issues with DankMaterialShell Go dependencies
    programs.dankMaterialShell = {
      enable = false;
      enableSystemMonitoring = true;
      enableClipboard = true;
      enableVPN = true;
      enableBrightnessControl = true;
      enableColorPicker = true;
      enableDynamicTheming = true;
      enableAudioWavelength = true;
      enableCalendarEvents = true;
      enableSystemSound = true;
      # enableKeybinds = true; # TODO: Update DankMaterialShell flake to support this
      # enableSpawn = true; # TODO: Update DankMaterialShell flake to support this
    };

    # Niri window manager
    services.displayManager.defaultSession = "niri";
    # programs.niri.agent.enable = false; # Option does not exist

    # Ghostty terminal emulator
    environment.systemPackages = with pkgs; [
      ghostty
    ];

    # Set ghostty as default terminal
    xdg.terminal-exec.settings.default = [ "ghostty.desktop" ];
    environment.sessionVariables.TERMINAL = "ghostty";

   # Shell Environment
   programs.fish.enable = true;

   # Authentication & Security - 1Password integration
   # Using NixOS built-in modules per 1Password developer docs:
   # https://developer.1password.com/docs/cli/get-started/#install
   programs.onepassword-desktop = {
     enable = true;
     polkitPolicyOwners = [ "hbohlen" ];
   };

   # Home Manager configuration
   # TODO: Fix CUDA unfree dependency issue before enabling
   # home-manager.users.hbohlen = { pkgs, lib, ... }: {
   #   imports = [
   #     ../../home/hbohlen/home.nix
   #     ../../modules/home-manager
   #   ];
   # };

   # State version - DO NOT CHANGE after installation
   system.stateVersion = "25.05";
}
