# hosts/yoga/default.nix
# Yoga host configuration using nixos-facter-modules for automatic hardware detection

{
  config,
  lib,
  pkgs,
  ...
}:

{
  imports = [
    # Core modules
    ../../modules

    # Hardware detection using nixos-facter-modules
    # This automatically configures network, graphics, USB, and other hardware
    # based on the hardware report generated by nixos-facter
  ];

  # Hostname
  networking.hostName = "yoga";

  # Bootloader - GRUB with UEFI support
  boot.loader.grub = {
    enable = true;
    efiSupport = true;
    efiInstallAsRemovable = true;
    device = "nodev";
    extraConfig = ''
      serial --unit=0 --speed=115200 --word=8 --parity=no --stop=1
      terminal_input serial console
      terminal_output serial console
    '';
  };

  # SSH configuration - hardened
  services.openssh = {
    enable = true;
    settings = {
      PermitRootLogin = "prohibit-password";
      PasswordAuthentication = false;
      KbdInteractiveAuthentication = false;
    };
  };

  # User configuration
  users.users.root = {
    # OpNix writes to /root/.ssh/authorized_keys
  };

  users.users.hbohlen = {
    isNormalUser = true;
    extraGroups = [
      "wheel" # sudo access
      "podman" # container management
      "docker" # docker CLI compat
    ];
    # OpNix writes to /home/hbohlen/.ssh/authorized_keys
  };

  # Sudo configuration - passwordless for wheel group
  security.sudo.wheelNeedsPassword = false;

  # Automatic garbage collection
  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than 30d";
  };

  # Optimize nix store
  nix.settings = {
    auto-optimise-store = true;
    experimental-features = [
      "nix-command"
      "flakes"
    ];
  };

  # Basic file systems for configuration testing
  # TODO: Replace with actual disko configuration for production
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "btrfs";
    options = [ "subvol=root" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
  };

  # State version - DO NOT CHANGE after installation
  system.stateVersion = "25.05";
}
