# modules/hardware/detection-scripts.nix
# Provides hardware detection and diagnostic scripts
# NixOS-native replacement for CachyOS shell scripts
#
# These scripts replace the bash/fish inventory scripts with declarative Nix
# They can be called at runtime for hardware diagnostics and troubleshooting

{ config, lib, pkgs, ... }:

with lib;

{
  environment.systemPackages = with pkgs; [
    # Hardware detection tools (system-level)
    dmidecode  # SMBIOS/DMI table decoder
    lshw       # List hardware
    lscpu      # CPU info
    lspci      # PCI devices
    lsblk      # Block devices
    lsusb      # USB devices
    btrfs-progs  # BTRFS utilities
    nvme-cli   # NVMe device info
    util-linux # Standard utilities
    pciutils   # PCI tools
    usbutils   # USB tools
    acpi       # Power/ACPI info
    
    # Diagnostic scripts
    (pkgs.writeScriptBin "hardware-inventory" ''
      #!/usr/bin/env bash
      # Hardware Inventory Report for NixOS ASUS ROG Zephyrus
      # Generated by declarative NixOS hardware detection module

      set -euo pipefail

      echo "=== NixOS Hardware Inventory ===" 
      echo "Generated: $(date)"
      echo "Hostname: $(hostname)"
      echo ""

      # CPU Information
      echo "=== CPU Information ==="
      if command -v lscpu &> /dev/null; then
        lscpu | grep -E "Model name|Architecture|CPU\(s\)|Core|Socket|MHz|Flags" | head -20
      else
        echo "lscpu not found"
      fi
      echo ""

      # GPU Information
      echo "=== GPU Information (from PCI) ==="
      if command -v lspci &> /dev/null; then
        lspci | grep -iE "VGA|3D|Display" || echo "No dedicated GPU detected"
      else
        echo "lspci not found"
      fi
      echo ""

      # Memory Information
      echo "=== Memory Information ==="
      if command -v dmidecode &> /dev/null; then
        sudo dmidecode -t memory 2>/dev/null | grep -E "Size:|Speed:|Type:|Manufacturer|Locator" | head -16 || echo "Requires root access"
      fi
      free -h
      echo ""

      # Storage Devices
      echo "=== Storage Devices ==="
      if command -v lsblk &> /dev/null; then
        lsblk -d -o NAME,SIZE,MODEL,ROTA,TRAN,SUBSYSTEMS 2>/dev/null || lsblk -d -o NAME,SIZE,MODEL,ROTA,TRAN
      fi
      echo ""

      # NVMe Details
      echo "=== NVMe Devices ==="
      if command -v nvme &> /dev/null; then
        nvme list 2>/dev/null || echo "nvme-cli not available or no NVMe devices"
      fi
      for path in /sys/block/nvme*/device/model; do
        if [ -f "$path" ]; then
          device=$(echo "$path" | grep -oE 'nvme[0-9]+')
          echo "$device: $(cat "$path")"
        fi
      done
      echo ""

      # BTRFS Information
      echo "=== BTRFS Configuration ==="
      if command -v btrfs &> /dev/null; then
        # List mounted BTRFS filesystems
        mount | grep btrfs || echo "No BTRFS filesystems mounted"
        echo ""
        # List subvolumes if root is BTRFS
        if sudo btrfs subvolume list / 2>/dev/null | grep -q .; then
          echo "BTRFS Subvolumes:"
          sudo btrfs subvolume list / 2>/dev/null || echo "Cannot list subvolumes (requires root)"
        else
          echo "Root filesystem is not BTRFS or BTRFS tools unavailable"
        fi
      else
        echo "btrfs-progs not installed"
      fi
      echo ""

      # Power Management
      echo "=== Power Management ==="
      echo "asusctl: $(command -v asusctl &>/dev/null && echo 'INSTALLED' || echo 'NOT FOUND')"
      echo "power-profiles-daemon: $(command -v powerprofilesctl &>/dev/null && echo 'INSTALLED' || echo 'NOT FOUND')"
      echo "acpi: $(command -v acpi &>/dev/null && echo 'INSTALLED' || echo 'NOT FOUND')"
      echo ""

      # Battery Information (if available)
      echo "=== Battery Status ==="
      if command -v acpi &> /dev/null; then
        acpi 2>/dev/null || echo "ACPI not available"
      fi
      if [ -d /sys/class/power_supply ]; then
        for battery in /sys/class/power_supply/BAT*/; do
          if [ -d "$battery" ]; then
            name=$(basename "$battery")
            echo "$name:"
            test -f "$battery/status" && echo "  Status: $(cat "$battery/status")"
            test -f "$battery/capacity" && echo "  Capacity: $(cat "$battery/capacity")%"
            test -f "$battery/charge_control_end_threshold" && echo "  Charge Limit: $(cat "$battery/charge_control_end_threshold")%"
          fi
        done
      fi
      echo ""

      # Network Devices
      echo "=== Network Devices ==="
      if command -v lspci &> /dev/null; then
        lspci | grep -i network || echo "No network devices detected"
      fi
      echo ""

      # ASUS ROG Specific Hardware
      echo "=== ASUS ROG Hardware Detection ==="
      if [ -d /sys/devices/platform/asus-nb-wmi ]; then
        echo "ASUS WMI: DETECTED"
      else
        echo "ASUS WMI: NOT DETECTED"
      fi
      test -f /sys/devices/platform/asus-nb-wmi/kbd_backlight && echo "Keyboard backlight: SUPPORTED" || echo "Keyboard backlight: NOT DETECTED"
      echo ""

      # Thermal Zones
      echo "=== Thermal Zones ==="
      if [ -d /sys/class/thermal ]; then
        for zone in /sys/class/thermal/thermal_zone*; do
          if [ -f "$zone/type" ]; then
            name=$(basename "$zone")
            type=$(cat "$zone/type")
            if [ -f "$zone/temp" ]; then
              temp=$(($(cat "$zone/temp") / 1000))
              echo "$name: $type - ''${temp}°C"
            else
              echo "$name: $type - (no temp)"
            fi
          fi
        done
      fi
      echo ""

      # Kernel Modules
      echo "=== Loaded ASUS Kernel Modules ==="
      lsmod | grep -i asus || echo "No ASUS modules loaded"
      echo ""

      echo "=== Hardware Inventory Complete ==="
    '')

    (pkgs.writeScriptBin "verify-hardware" ''
      #!/usr/bin/env bash
      # Verification script for hardware detection
      # Run after hardware-inventory to validate critical components

      set -euo pipefail

      INVENTORY_FILE="''${1:-/tmp/hardware-inventory.txt}"

      echo "=== Hardware Verification ==="
      echo "Using inventory: $INVENTORY_FILE"
      echo ""

      if [ ! -f "$INVENTORY_FILE" ]; then
        echo "ERROR: Inventory file not found: $INVENTORY_FILE"
        echo "Run 'hardware-inventory' first to generate it"
        exit 1
      fi

      PASSED=0
      FAILED=0

      test_section() {
        local name=$1
        local pattern=$2
        
        if grep -q "$pattern" "$INVENTORY_FILE"; then
          echo "✓ $name: PASSED"
          ((PASSED++))
        else
          echo "✗ $name: FAILED"
          ((FAILED++))
        fi
      }

      # Run verification tests
      test_section "CPU detection" "Model name"
      test_section "NVMe detection" "nvme"
      test_section "ASUS WMI detection" "ASUS WMI"
      test_section "Power management tools" "asusctl"
      test_section "BTRFS support" "btrfs"
      test_section "Battery detection" "Capacity"

      echo ""
      echo "=== Verification Summary ==="
      echo "Passed: $PASSED"
      echo "Failed: $FAILED"
      
      [ $FAILED -eq 0 ] && echo "All checks passed!" || echo "Some checks failed. Review output above."
    '')

    (pkgs.writeScriptBin "power-status" ''
      #!/usr/bin/env bash
      # Quick power and battery status report

      echo "=== Power Status Report ==="
      echo "Time: $(date)"
      echo ""

      if command -v powerprofilesctl &>/dev/null; then
        echo "Current profile:"
        powerprofilesctl get
        echo ""
        echo "Available profiles:"
        powerprofilesctl list
      fi
      echo ""

      echo "Power supplies:"
      for ps in /sys/class/power_supply/*/; do
        name=$(basename "$ps")
        type=$(cat "$ps/type" 2>/dev/null || echo "unknown")
        if [ -f "$ps/capacity" ]; then
          capacity=$(cat "$ps/capacity")
          echo "  $name ($type): $capacity%"
        else
          echo "  $name ($type)"
        fi
      done
      echo ""

      if command -v acpi &>/dev/null; then
        echo "ACPI Info:"
        acpi 2>/dev/null || echo "Not available"
      fi
    '')
  ];

  # Enable asusctl service if on ASUS hardware
  # (already defined in asus-rog.nix module, included here for reference)
}
